version: '3.9'
# this docker compose is for postgressql db in development enviroment only
services:
  postgres:
    image: postgres:16-alpine3.17
    container_name: auth-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  postgres-data:
