CREATE TABLE "SystemUser"(
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Password" varchar(255) NOT NULL,
  "Email" varchar(150) UNIQUE NOT NULL,
  "RestartAccount" BOOLEAN DEFAULT FALSE,
  "ConfirmAccount" BOOLEAN DEFAULT FALSE,
  "FirstName" varchar(100) NOT NULL,
  "LastName" varchar(100) NOT NULL,
  "BadConduct" INTEGER,
  "Token" varchar(6),
  "Banned" BOOLEAN GENERATED ALWAYS AS (CASE WHEN "BadConduct" > 7 THEN TRUE ELSE FALSE END) STORED,
  "Img" BYTEA NOT NULL DEFAULT '\\x',
  "Club" VARCHAR(20),
  "Rol" VARCHAR(20) NOT NULL
);

CREATE TABLE "FeedBack" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Message" varchar(200)
);

CREATE TABLE "Article" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar(100) NOT NULL,
  "Content" Text NOT NULL,
  "Description" varchar(200),
  "Keywords" varchar(60),
  "CreateAt" TimeStamp,
  "ArticleState" VARCHAR(20) NOT NULL,
  "ArticleType" VARCHAR(20) NOT NULL,
  "SystemUserId" INTEGER NOT NULL,
  "AdminReviewId" INTEGER
);

CREATE TABLE "Reaction" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "CreateAt" TimeStamp,
  "Content" varchar(300) NOT NULL,
  "SystemUserId" INTEGER NOT NULL,
  "ArticleId" INTEGER NOT NULL,
  "ParentId" INTEGER DEFAULT 0
);

CREATE TABLE "Notification" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "CreateAt" TimeStamp,
  "Type" Varchar(20),
  "ToUser" INTEGER,
  "SystemUserId" INTEGER,
  "ArticleId" INTEGER,
  "IsRead" BOOLEAN DEFAULT FALSE
);

 
ALTER TABLE "Article" ADD FOREIGN KEY ("SystemUserId") REFERENCES "SystemUser" ("Id");

ALTER TABLE "Article" ADD FOREIGN KEY ("AdminReviewId") REFERENCES "SystemUser" ("Id");

ALTER TABLE "Reaction" ADD FOREIGN KEY ("SystemUserId") REFERENCES "SystemUser" ("Id");

ALTER TABLE "Reaction" ADD FOREIGN KEY ("ArticleId") REFERENCES "Article" ("Id");

ALTER TABLE "Notification" ADD FOREIGN KEY ("SystemUserId") REFERENCES "SystemUser" ("Id");
